# Generated by Django 5.0.7 on 2024-08-02 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='data',
            field=models.DateTimeField(),
        ),
    ]
